name: flappy_bombs
description: A Giantbomb video and forum browser written in flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dioc: ^0.1.4
  resolve: ^0.2.2
  shared_preferences: ^0.4.3
  flutter_secure_storage: ^3.1.3
  intro_views_flutter: ^2.4.0
  image_picker: ^0.5.0+3
  kt_dart: ^0.5.0
  quiver: ^2.0.1
  cupertino_icons: ^0.1.2
  tinano:
  rxdart: ^0.20.0
  rx_command: ^4.1.1
  rx_widgets: ^2.2.0
  fimber: ^0.1.8
  tuple: ^1.0.2
  fluro: ^1.4.0
  sealed_unions: ^3.0.0
  flutter_advanced_networkimage:
  equatable: ^0.1.0
  flutter_stetho: ^0.2.2
  url_launcher: ^5.0.1
  bloc: ^0.8.3
  flutter_bloc: ^0.5.4
  flutter_android_pip: ^0.0.2
  video_player: ^0.10.0+1
  share: ^0.6.0+1
  flutter_svg: ^0.10.3
  flutter_local_notifications: ^0.5.1
  flutter_spinkit: ^3.1.0
#  permission_handler: ^2.1.2
  splashscreen: ^1.2.0
  pull_to_refresh: ^1.1.6
  flutter_downloader: ^1.1.6
  flutter_politburo:
    git:
      url: git@github.com:Wyrmix/flutter_politburo.git
  http: ^0.12.0+1
  auto_size_text: ^0.3.0
  card_settings: ^1.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  dherkin2: ^1.0.1+1
  build_runner:
  tinano_generator:
  test: ^1.5.1
  mockito:


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
